services:
  go_app_dev:
    image: go_app_dev
    volumes:
      - .:/app # Colocar a pasta atual app para ser compartilhada
      - external-storage:/media/uploads # Storage para ser compartilhado entre containers
    tty: true # Modo interativo para logar no container
    stdin_open: true # Permitir digitar comando no bash

  postgres:
    image: postgres:13
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "converter"
      POSTGRES_HOST: "postgres"
      POSTGRES_SSL_MODE: "disable"
    volumes:
      - .docker/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: teste@teste.com
      PGADMIN_DEFAULT_PASSWORD: teste

volumes:
  external-storage:
    external: true