services:
  go_app_dev:
    image: go_app_dev
    volumes:
      - .:/app # Colocar a pasta atual app para ser compartilhada
      - external-storage:/media/uploads # Storage para ser compartilhado entre containers
    tty: true # Modo interativo para logar no container
    stdin_open: true # Permitir digitar comando no bash

  postgres:
    image: postgres:13
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "converter"
      POSTGRES_HOST: "postgres"
      POSTGRES_SSL_MODE: "disable"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
      CONVERSION_EXCHANGE: "conversion_exchange"
      CONVERSION_QUEUE: "video_conversion_queue"
      CONVERSION_KEY: "conversion"
    volumes:
      - .docker/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: teste@teste.com
      PGADMIN_DEFAULT_PASSWORD: teste

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

volumes:
  external-storage:
    external: true