include:
  - ../postgres/docker-compose.yaml
  - ../rabbitmq/docker-compose.yaml
  # - ../nginx/docker-compose.yaml

services:

  django:
    build: .
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgres://postgres:root@postgres:5432/django_videos
      #- DATABASE_URL=sqlite:///db.sqlite3\
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - ASSETS_URL=http://host.docker.internal:9000/media/uploads
    volumes:
      - .:/home/my-user/app
      - external-storage:/media/uploads # Storage para ser compartilhada entre containers
    extra_hosts:
      - host.docker.internal:host-gateway # Permitir conversar com a aplicação do rabbitmq (gateway da rede do docker, aonde os containers batem para poderem fazer acessos externos)
    
  change_media_permission:
    build: .
    user: root
    command: chown -R 1000:1000 /media/uploads
    volumes:
      - external-storage:/media/uploads
    depends_on:
      - django
  
volumes:
  external-storage:
    external: true